
package com.thalesgroup.rtti._2016_02_16.ldb;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ldb", targetNamespace = "http://thalesgroup.com/RTTI/2016-02-16/ldb/", wsdlLocation = "https://lite.realtime.nationalrail.co.uk/OpenLDBWS/wsdl.aspx?ver=2016-02-16")
public class Ldb
    extends Service
{

    private final static URL LDB_WSDL_LOCATION;
    private final static WebServiceException LDB_EXCEPTION;
    private final static QName LDB_QNAME = new QName("http://thalesgroup.com/RTTI/2016-02-16/ldb/", "ldb");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://lite.realtime.nationalrail.co.uk/OpenLDBWS/wsdl.aspx?ver=2016-02-16");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LDB_WSDL_LOCATION = url;
        LDB_EXCEPTION = e;
    }

    public Ldb() {
        super(__getWsdlLocation(), LDB_QNAME);
    }

    public Ldb(WebServiceFeature... features) {
        super(__getWsdlLocation(), LDB_QNAME, features);
    }

    public Ldb(URL wsdlLocation) {
        super(wsdlLocation, LDB_QNAME);
    }

    public Ldb(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LDB_QNAME, features);
    }

    public Ldb(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Ldb(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LDBServiceSoap
     */
    @WebEndpoint(name = "LDBServiceSoap")
    public LDBServiceSoap getLDBServiceSoap() {
        return super.getPort(new QName("http://thalesgroup.com/RTTI/2016-02-16/ldb/", "LDBServiceSoap"), LDBServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LDBServiceSoap
     */
    @WebEndpoint(name = "LDBServiceSoap")
    public LDBServiceSoap getLDBServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://thalesgroup.com/RTTI/2016-02-16/ldb/", "LDBServiceSoap"), LDBServiceSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns LDBServiceSoap
     */
    @WebEndpoint(name = "LDBServiceSoap12")
    public LDBServiceSoap getLDBServiceSoap12() {
        return super.getPort(new QName("http://thalesgroup.com/RTTI/2016-02-16/ldb/", "LDBServiceSoap12"), LDBServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LDBServiceSoap
     */
    @WebEndpoint(name = "LDBServiceSoap12")
    public LDBServiceSoap getLDBServiceSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://thalesgroup.com/RTTI/2016-02-16/ldb/", "LDBServiceSoap12"), LDBServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LDB_EXCEPTION!= null) {
            throw LDB_EXCEPTION;
        }
        return LDB_WSDL_LOCATION;
    }

}
